/* MODULO CORRES PONDIENTE A LAS CALIFICACIONES */
package Interfaces;
/* @author 1354951  */

public class Grades extends javax.swing.JInternalFrame {

    /**
     * Creates new form Grades
     */
    public Grades() {
        initComponents();
        setSize(1248,663);
        setLocation(0,36);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneFondo = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jButtonNotas = new javax.swing.JButton();
        jButtonDefinitiva = new javax.swing.JButton();

        jDesktopPaneFondo.setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CALIFICACIONES ");

        jButtonSalir.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/salir.png"))); // NOI18N
        jButtonSalir.setText("SALIR");
        jButtonSalir.setBorder(null);
        jButtonSalir.setBorderPainted(false);
        jButtonSalir.setContentAreaFilled(false);
        jButtonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonNotas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonNotas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/calificaciones.png"))); // NOI18N
        jButtonNotas.setText("INGRESAR NOTAS");
        jButtonNotas.setBorder(null);
        jButtonNotas.setBorderPainted(false);
        jButtonNotas.setContentAreaFilled(false);
        jButtonNotas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNotas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNotas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNotasActionPerformed(evt);
            }
        });

        jButtonDefinitiva.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonDefinitiva.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDefinitiva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/definitiva.png"))); // NOI18N
        jButtonDefinitiva.setText("DEFINITIVA");
        jButtonDefinitiva.setBorder(null);
        jButtonDefinitiva.setBorderPainted(false);
        jButtonDefinitiva.setContentAreaFilled(false);
        jButtonDefinitiva.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDefinitiva.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonDefinitiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDefinitivaActionPerformed(evt);
            }
        });

        jDesktopPaneFondo.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneFondo.setLayer(jButtonSalir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneFondo.setLayer(jButtonNotas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneFondo.setLayer(jButtonDefinitiva, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneFondoLayout = new javax.swing.GroupLayout(jDesktopPaneFondo);
        jDesktopPaneFondo.setLayout(jDesktopPaneFondoLayout);
        jDesktopPaneFondoLayout.setHorizontalGroup(
            jDesktopPaneFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDesktopPaneFondoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jDesktopPaneFondoLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jButtonNotas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(jButtonDefinitiva, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
        jDesktopPaneFondoLayout.setVerticalGroup(
            jDesktopPaneFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneFondoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(87, 87, 87)
                .addGroup(jDesktopPaneFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonNotas)
                    .addComponent(jButtonDefinitiva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneFondo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneFondo)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // SALIR AL PRINCIPAL:
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonDefinitivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDefinitivaActionPerformed
        Observations obs = new Observations();
        obs.setBounds(300, 100, 550, 400);
        obs.setVisible(true);
        jDesktopPaneFondo.add(obs);
    }//GEN-LAST:event_jButtonDefinitivaActionPerformed

    private void jButtonNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNotasActionPerformed
        ActivityGrades actGra = new ActivityGrades();
        actGra.setBounds(300, 100, 450, 550);
        actGra.setVisible(true);
        jDesktopPaneFondo.add(actGra);
    }//GEN-LAST:event_jButtonNotasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDefinitiva;
    private javax.swing.JButton jButtonNotas;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JDesktopPane jDesktopPaneFondo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
