/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Resources.Connection;
import java.sql.ResultSet;

/**
 *
 * @author ACER
 */
public class StudentsDegree extends javax.swing.JInternalFrame {

    /**
     * Creates new form StudentsDegree
     */
    Connection con ;
    String idGrade[];
    public StudentsDegree() {
        initComponents();
        setSize(1237,629);
        setLocation(0,0);
        con = new Connection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboGroups = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnPdf = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Reportes estudiantes por grado");
        setToolTipText("");
        getContentPane().setLayout(null);

        getContentPane().add(cboGroups);
        cboGroups.setBounds(136, 60, 105, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(35, 121, 322, 120);

        btnPdf.setText("GENERAR PDF");
        getContentPane().add(btnPdf);
        btnPdf.setBounds(141, 259, 101, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

public void loadCb(){
    try {
        ResultSet resul = con.consultDB("SELECT COUNT(*) cuenta FROM grupo");
        if(resul.next()){
            idGrade = new String[resul.getInt("cuenta")];
        }
    } catch (Exception e) {
    }
    int i = 0;
    try {
        ResultSet rs = con.consultDB("SELECT * FROM grupo");
        while(rs.next()){
            idGrade[i] = rs.getString("idGrupo");
            cboGroups.addItem(rs.getString("Nombre"));
        }
    } catch (Exception e) {
    }
}       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPdf;
    private javax.swing.JComboBox<String> cboGroups;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
