/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author JH0N4T4N
 */
public class SubjectGrade extends javax.swing.JInternalFrame {

    /**
     * Creates new form SubjectGrade
     */
    public SubjectGrade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();

        getContentPane().setLayout(null);

        jDesktopPane1.setBackground(new java.awt.Color(0, 0, 255));
        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 0, 670, 501);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    // End of variables declaration//GEN-END:variables
}
